#!/usr/bin/env bash
# Configures domain zone so that the subdomain www points to my load-balancer IP

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
        subdomains=(www lb-01 web-01 web-02)
else
        subdomains=($subdomain)
fi
for sub in "${subdomains[@]}"; do
        record_type=$(dig +short $sub.$domain | awk '{print $4}')
        destination=$(dig +short $sub.$domain | awk '{print $5}')
        echo "The subdomain $sub is a $record_type record and points tp $destination"
done
