#!/usr/bin/env bash
# Configures domain zone so that the subdomain www points to my load-balancer IP
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    record=$(dig +short $sub.$domain)
    type=$(dig $sub.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    echo "The subdomain $sub is a $type record and points to $record"

done
