#!/usr/bin/env bash
# Configures domain zone so that the subdomain www points to my load-balancer IP

print_domain_subdomain () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "54.237.52.82"
    print_domain_subdomain "lb-01.$1" "54.237.52.82"
    print_domain_subdomain "web-01.$1" "100.25.179.193"
    print_domain_subdomain "web-02.$1" "54.174.161.74"
fi
