#!/usr/bin/env bash
#creates a certifacte

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    tune.ssl.default-dh-param 2048
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_frontend
    bind *:443 ssl crt /etc/letsencrypt/live/www.teechistudio.tech.pem
    http-request add-header X-Forwarded-Proto https
    http-request redirect scheme https if !{ ssl_fc }
    use_backend http_holberton

backend http_backend
    redirect scheme https if !{ ssl_fc }
    server 254410-web-01 100.25.179.193:80
    server 254410-web-02 54.174.161.74:80
