#!/usr/bin/env bash
# Configures a brand a new Ubuntu machine for and installs nginx

sudo apt-get update
sudo apt-get upgrade -y

sudo apt-get install -y nginx

sudo sh -c "cat > /etc/nginx/sites-available/default" <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        return 200 "Hello, this is web server: \${HOSTNAME}\n";
        add_header X-Served-By \${HOSTNAME};
    }
}
EOL

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo systemctl restart nginx
