#!/usr/bin/env bash
# Custom 404 page that contains a string

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "server {
        listen 80;
        listen [::]:80 default_server;
        add_header X-Served-by $HOSTNAME;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://github.com/tannyaarr;
        }
        error_page 404/404.html;
        location = /404.html {
                root /var/www/html
                internal;
        }
}" sudo tee /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
