#!/usr/bin/env bash
# Configures a brand a new Ubuntu machine

sudo apt-get update
sudo apt-get install nginx -y

# Configure Nginx to use the custom error page
sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo sed -i 's/#location = \/404.html {/location = \/404.html {/' /etc/nginx/sites-available/default
sudo sed -i 's/#    internal;/    internal;/' /etc/nginx/sites-available/default
sudo sed -i 's/#}/}/' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
