#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y haproxy

cat << EOF >  /etc/haproxy/haproxy.cfg

frontend hhtp-in
	bind *:80
	mode http
	default_backend servers

backend servers
	mode http
	balance roundrobin
	server web-01 100.25.179.193-web-01:80 check
	server web-02 52.86.33.156-web-02:80 check
EOF
echo "ENABLED =1" | sudo tee /etc/default/haproxy
sudo systemctl restart haproxy
