#!/usr/bin/env bash
# Generates a MySQL dump and creates a cmpressed archive out of it

mysql_password=$1
timestamp=$(date + "%d-%m-%y")
mysqldump -u root -p "${mysql_password}" --all-databases | gzip > "backup_${timestamp}.sgl.gz"
