#!/usr/bin/env bash
# Generates a MySQL dump and creates a cmpressed archive out of it

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > back.sql
tar -czvf "$file_name" back.sql
