#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing it PID
# Displays 'To infinity and beyond' indefinitely
# Displays 'I hate to kill command' when receiving a SIGTERM signal
# Displays 'Y U no love me?' when receiving s SIGINT
# Deletes the /var/run/myscript.pid and terminates itself
#+ when receiving a SIGQUIT signal 


echo $$ > /var/run/myscript.pid

terminator() {
	rm /var/run/myscript.pid
	exit 
}

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
done
