#!/usr/bin/env bash
# Script that manages "manage_my_process"
# When passing the argument start:
#+ Starts manage_my_process
#+ Creates a file containing its PID in /var/run/my_process.pid
#+ Displays manage_my_process started
# When passing the argument stop:
#+ Stops manage_my_process
#+ Deletes the file /var/run/my_process.pid
#+ Displays manage_my_process stopped
# When passing the argument restart
#+ Stops manage_my_process
#+ Deletes the file /var/run/my_process.pid
#+ Starts manage_my_process
#+ Creates a file containing its PID in /var/run/my_process.pid
#+ Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

PID_FILE="/var/run/my_process.pid"
MANAGE_SCRIPT="./manage_my_process"

function start_process 
{	if [ -e "$PID_FILE" ]; then
	 	echo "Error: manage_my_process is already running (PID $(cat $PID_FILE))"
	else
		$MANAGE_SCRIPT &
        	echo $! >> $PID_FILE
        	echo "manage_my_process started"
    	fi
}

function stop_process
{	if [ -e "$PID_FILE" ]; then
        	pid=$(cat $PID_FILE)
        	kill $pid
        	rm -f $PID_FILE
    else
		echo "manage_my_process stopped"
    fi
}

function restart_process
{	stop_process
    	start_process
    	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start_process
        	;;
    	stop)
        	stop_process
        	;;
    	restart)
        	restart_process
        	;;
    	*)
        	echo "Usage: $0 {start|stop|restart}"
        	exit 1
        	;;
esac

