#!/usr/bin/env bash
#This scrip stops the 4-to_infinity_and_beyond

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n $pid ]]; then
	echo "Stopping 4-to_infinity_and_beyond process (PID: $pid)..."
	kill "$pid"
	echo "Process stopped successfully."
else
	echo "4-to_infinity_and_beyond process is not running"
fi
