#!/usr/bin/env bash
# Writes "i am alive" indefinitely to the file /tmp/my_process
# In between every "i am alive" message, the program should
#+ pause for 2 seconds

while true
do
	echo "I am alive" >> /tmp/my_process
	sleep 2
done
