#!/usr/bin/env bash
#A script that displays numbers from 1 to 100 and displays fizzbuzz for multiples of 5 and 3, fizz for multiples of 3, buzz multiples of 5

for ((i=1; i<=100; i++)); do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
