#!/usr/bin/env bash
#This script that displays the content of the file /etc/passwd

while IFS=":" read -r username _ uid _ _ home _; do
	echo "Username: $username"
	echo "User ID: $uid"
	echo "Home Directory: $home"
	echo "_______________________"
done < /etc/passwd
