#!/usr/bin/env bash
#This script displays messages based on loop

counter=1

while [ $counter -lt 10 ]; do
	if [ $counter -eq 3 ]; then
		echo "bad luck"
	elif [ $counter -eq 7 ]; then
		echo "goodluck"
	else
		echo "Best School"
	fi
	((counter++))
done
