#!/usr/bin/env bash
#This script displays time in 12 hour format

hours=0
minutes=1

while [ $hours -le 12 ]; do
	while [ $minutes -le 59 ]; do
		formatted_hours=$(printf "%02d" $hours)
		formatted_minutes=$(printf "%02d" $minutes)

		echo "$formatted_hours:$formatted_minutes"
		((minutes++))
	done
	minutes=1
	((hours++))
done
