#!/usr/bin/env bash
# This script displays time in 12-hour format

hours=1

while [ $hours -le 12 ]; do
    minutes=0

    while [ $minutes -le 59 ]; do
        formatted_hours=$(printf "%02d" $hours)
        formatted_minutes=$(printf "%02d" $minutes)

        echo "$formatted_hours:$formatted_minutes"
        ((minutes++))
    done

    ((hours++))
done
