#!/usr/bin/env bash
# bash script that configures an ubuntu server with the below:
# localhost resolves to 127.0.0.2
# facebook.com resolves 8.8.8.8

if [ "$(id -u)" -ne 0 ]; then
	echo "please run the script with sudo or as root."
	exit 1
fi

localhost_mapping="127.0.0.2 localhost"
facebook_mapping="8.8.8.8 facebook.com"

cp /etc/hosts /etc/hosts.backup

sed -i "s/^127\.0\.0\.1[[:space:]]\+localhost$/$localhost_mapping/" /etc/hosts
sed -i "s/^.*[[:space:]]\+facebook\.com$/$facebook_mapping/" /etc/hosts

echo -e "$localhost_mapping\n$facebook_mapping" >> /etc/hosts

echo "hosts file configured successfully"
