#!/usr/bin/env bash

if [ "$(id -u)" -ne 0 ]; then
	echo "please run the script with sudo or as root."
	exit 1
fi

localhost_mapping="127.0.0.2 localhost"
facebook_mapping="8.8.8.8 facebook.com"

cp /etc/hosts /etc/hosts.backup

echo -e "$localhost_mapping\n$facebook_mapping" >> /etc/hosts

echo "hosts file configured successfully"
