#!/usr/bin/env bash

if [ "$(id -u)" -ne 0 ]; then
	echo "Please run the script with sudo or as root."
	exit 1
fi

ipv4_ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

echo "Active IPv4 IPs:"
echo "$ipv4_ips"
