#!/usr/bin/env bash
# Nginx running as the nginx user
apt- get update
apt-get install -y nginx
sed -i -e 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf
sed -i -e 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
pkill nginx
nginx -g 'daemon off;'
